services:
  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: "http://user-service:8000"
      POST_SERVICE_URL: "post-service:50051"
    depends_on:
      - user-service
      - post-service

  user-service:
    build: ./user_service
    container_name: user-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./user_service/.env
    depends_on:
      db:
        condition: service_healthy
        
  post-service:
      build: ./post_service
      container_name: post-service
      restart: always
      ports:
        - "50051:50051"
      env_file:
        - ./post_service/.env
      depends_on:
        db:
          condition: service_healthy
    
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
