// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/statistics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopRequest_StatType int32

const (
	GetTopRequest_VIEWS    GetTopRequest_StatType = 0
	GetTopRequest_LIKES    GetTopRequest_StatType = 1
	GetTopRequest_COMMENTS GetTopRequest_StatType = 2
)

// Enum value maps for GetTopRequest_StatType.
var (
	GetTopRequest_StatType_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	GetTopRequest_StatType_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x GetTopRequest_StatType) Enum() *GetTopRequest_StatType {
	p := new(GetTopRequest_StatType)
	*p = x
	return p
}

func (x GetTopRequest_StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTopRequest_StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_statistics_proto_enumTypes[0].Descriptor()
}

func (GetTopRequest_StatType) Type() protoreflect.EnumType {
	return &file_proto_statistics_proto_enumTypes[0]
}

func (x GetTopRequest_StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTopRequest_StatType.Descriptor instead.
func (GetTopRequest_StatType) EnumDescriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{5, 0}
}

type GetPostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint32                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsRequest) Reset() {
	*x = GetPostStatsRequest{}
	mi := &file_proto_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsRequest) ProtoMessage() {}

func (x *GetPostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatsRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         uint32                 `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Likes         uint32                 `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      uint32                 `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsResponse) Reset() {
	*x = GetPostStatsResponse{}
	mi := &file_proto_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsResponse) ProtoMessage() {}

func (x *GetPostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPostStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostStatsResponse) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetPostStatsResponse) GetLikes() uint32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *GetPostStatsResponse) GetComments() uint32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type GetPostDynamicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint32                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDynamicsRequest) Reset() {
	*x = GetPostDynamicsRequest{}
	mi := &file_proto_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDynamicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDynamicsRequest) ProtoMessage() {}

func (x *GetPostDynamicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDynamicsRequest.ProtoReflect.Descriptor instead.
func (*GetPostDynamicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostDynamicsRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetDynamicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DayCount            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicsResponse) Reset() {
	*x = GetDynamicsResponse{}
	mi := &file_proto_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicsResponse) ProtoMessage() {}

func (x *GetDynamicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicsResponse.ProtoReflect.Descriptor instead.
func (*GetDynamicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *GetDynamicsResponse) GetData() []*DayCount {
	if x != nil {
		return x.Data
	}
	return nil
}

type DayCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayCount) Reset() {
	*x = DayCount{}
	mi := &file_proto_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayCount) ProtoMessage() {}

func (x *DayCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayCount.ProtoReflect.Descriptor instead.
func (*DayCount) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *DayCount) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            GetTopRequest_StatType `protobuf:"varint,1,opt,name=by,proto3,enum=proto.GetTopRequest_StatType" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRequest) Reset() {
	*x = GetTopRequest{}
	mi := &file_proto_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRequest) ProtoMessage() {}

func (x *GetTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRequest.ProtoReflect.Descriptor instead.
func (*GetTopRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopRequest) GetBy() GetTopRequest_StatType {
	if x != nil {
		return x.By
	}
	return GetTopRequest_VIEWS
}

type GetTopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostStat            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPostsResponse) Reset() {
	*x = GetTopPostsResponse{}
	mi := &file_proto_statistics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsResponse) ProtoMessage() {}

func (x *GetTopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsResponse.ProtoReflect.Descriptor instead.
func (*GetTopPostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopPostsResponse) GetPosts() []*PostStat {
	if x != nil {
		return x.Posts
	}
	return nil
}

type PostStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint32                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStat) Reset() {
	*x = PostStat{}
	mi := &file_proto_statistics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStat) ProtoMessage() {}

func (x *PostStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStat.ProtoReflect.Descriptor instead.
func (*PostStat) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{7}
}

func (x *PostStat) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostStat) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserStat            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersResponse) Reset() {
	*x = GetTopUsersResponse{}
	mi := &file_proto_statistics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse) ProtoMessage() {}

func (x *GetTopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopUsersResponse) GetUsers() []*UserStat {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStat) Reset() {
	*x = UserStat{}
	mi := &file_proto_statistics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStat) ProtoMessage() {}

func (x *UserStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStat.ProtoReflect.Descriptor instead.
func (*UserStat) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{9}
}

func (x *UserStat) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStat) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_statistics_proto protoreflect.FileDescriptor

const file_proto_statistics_proto_rawDesc = "" +
	"\n" +
	"\x16proto/statistics.proto\x12\x05proto\".\n" +
	"\x13GetPostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\rR\x06postId\"^\n" +
	"\x14GetPostStatsResponse\x12\x14\n" +
	"\x05views\x18\x01 \x01(\rR\x05views\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\rR\x05likes\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\rR\bcomments\"1\n" +
	"\x16GetPostDynamicsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\rR\x06postId\":\n" +
	"\x13GetDynamicsResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.proto.DayCountR\x04data\"4\n" +
	"\bDayCount\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"n\n" +
	"\rGetTopRequest\x12-\n" +
	"\x02by\x18\x01 \x01(\x0e2\x1d.proto.GetTopRequest.StatTypeR\x02by\".\n" +
	"\bStatType\x12\t\n" +
	"\x05VIEWS\x10\x00\x12\t\n" +
	"\x05LIKES\x10\x01\x12\f\n" +
	"\bCOMMENTS\x10\x02\"<\n" +
	"\x13GetTopPostsResponse\x12%\n" +
	"\x05posts\x18\x01 \x03(\v2\x0f.proto.PostStatR\x05posts\"9\n" +
	"\bPostStat\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\rR\x06postId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"<\n" +
	"\x13GetTopUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.proto.UserStatR\x05users\"9\n" +
	"\bUserStat\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xda\x03\n" +
	"\x11StatisticsService\x12G\n" +
	"\fGetPostStats\x12\x1a.proto.GetPostStatsRequest\x1a\x1b.proto.GetPostStatsResponse\x12Q\n" +
	"\x14GetPostViewsDynamics\x12\x1d.proto.GetPostDynamicsRequest\x1a\x1a.proto.GetDynamicsResponse\x12Q\n" +
	"\x14GetPostLikesDynamics\x12\x1d.proto.GetPostDynamicsRequest\x1a\x1a.proto.GetDynamicsResponse\x12T\n" +
	"\x17GetPostCommentsDynamics\x12\x1d.proto.GetPostDynamicsRequest\x1a\x1a.proto.GetDynamicsResponse\x12?\n" +
	"\vGetTopPosts\x12\x14.proto.GetTopRequest\x1a\x1a.proto.GetTopPostsResponse\x12?\n" +
	"\vGetTopUsers\x12\x14.proto.GetTopRequest\x1a\x1a.proto.GetTopUsersResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_statistics_proto_rawDescOnce sync.Once
	file_proto_statistics_proto_rawDescData []byte
)

func file_proto_statistics_proto_rawDescGZIP() []byte {
	file_proto_statistics_proto_rawDescOnce.Do(func() {
		file_proto_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_statistics_proto_rawDesc), len(file_proto_statistics_proto_rawDesc)))
	})
	return file_proto_statistics_proto_rawDescData
}

var file_proto_statistics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_statistics_proto_goTypes = []any{
	(GetTopRequest_StatType)(0),    // 0: proto.GetTopRequest.StatType
	(*GetPostStatsRequest)(nil),    // 1: proto.GetPostStatsRequest
	(*GetPostStatsResponse)(nil),   // 2: proto.GetPostStatsResponse
	(*GetPostDynamicsRequest)(nil), // 3: proto.GetPostDynamicsRequest
	(*GetDynamicsResponse)(nil),    // 4: proto.GetDynamicsResponse
	(*DayCount)(nil),               // 5: proto.DayCount
	(*GetTopRequest)(nil),          // 6: proto.GetTopRequest
	(*GetTopPostsResponse)(nil),    // 7: proto.GetTopPostsResponse
	(*PostStat)(nil),               // 8: proto.PostStat
	(*GetTopUsersResponse)(nil),    // 9: proto.GetTopUsersResponse
	(*UserStat)(nil),               // 10: proto.UserStat
}
var file_proto_statistics_proto_depIdxs = []int32{
	5,  // 0: proto.GetDynamicsResponse.data:type_name -> proto.DayCount
	0,  // 1: proto.GetTopRequest.by:type_name -> proto.GetTopRequest.StatType
	8,  // 2: proto.GetTopPostsResponse.posts:type_name -> proto.PostStat
	10, // 3: proto.GetTopUsersResponse.users:type_name -> proto.UserStat
	1,  // 4: proto.StatisticsService.GetPostStats:input_type -> proto.GetPostStatsRequest
	3,  // 5: proto.StatisticsService.GetPostViewsDynamics:input_type -> proto.GetPostDynamicsRequest
	3,  // 6: proto.StatisticsService.GetPostLikesDynamics:input_type -> proto.GetPostDynamicsRequest
	3,  // 7: proto.StatisticsService.GetPostCommentsDynamics:input_type -> proto.GetPostDynamicsRequest
	6,  // 8: proto.StatisticsService.GetTopPosts:input_type -> proto.GetTopRequest
	6,  // 9: proto.StatisticsService.GetTopUsers:input_type -> proto.GetTopRequest
	2,  // 10: proto.StatisticsService.GetPostStats:output_type -> proto.GetPostStatsResponse
	4,  // 11: proto.StatisticsService.GetPostViewsDynamics:output_type -> proto.GetDynamicsResponse
	4,  // 12: proto.StatisticsService.GetPostLikesDynamics:output_type -> proto.GetDynamicsResponse
	4,  // 13: proto.StatisticsService.GetPostCommentsDynamics:output_type -> proto.GetDynamicsResponse
	7,  // 14: proto.StatisticsService.GetTopPosts:output_type -> proto.GetTopPostsResponse
	9,  // 15: proto.StatisticsService.GetTopUsers:output_type -> proto.GetTopUsersResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_statistics_proto_init() }
func file_proto_statistics_proto_init() {
	if File_proto_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_statistics_proto_rawDesc), len(file_proto_statistics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_statistics_proto_goTypes,
		DependencyIndexes: file_proto_statistics_proto_depIdxs,
		EnumInfos:         file_proto_statistics_proto_enumTypes,
		MessageInfos:      file_proto_statistics_proto_msgTypes,
	}.Build()
	File_proto_statistics_proto = out.File
	file_proto_statistics_proto_goTypes = nil
	file_proto_statistics_proto_depIdxs = nil
}
