// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/statistics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticsService_GetPostStats_FullMethodName            = "/proto.StatisticsService/GetPostStats"
	StatisticsService_GetPostViewsDynamics_FullMethodName    = "/proto.StatisticsService/GetPostViewsDynamics"
	StatisticsService_GetPostLikesDynamics_FullMethodName    = "/proto.StatisticsService/GetPostLikesDynamics"
	StatisticsService_GetPostCommentsDynamics_FullMethodName = "/proto.StatisticsService/GetPostCommentsDynamics"
	StatisticsService_GetTopPosts_FullMethodName             = "/proto.StatisticsService/GetTopPosts"
	StatisticsService_GetTopUsers_FullMethodName             = "/proto.StatisticsService/GetTopUsers"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	// 1. Получение общей статистики по посту
	GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*GetPostStatsResponse, error)
	// 2. Динамика просмотров по посту
	GetPostViewsDynamics(ctx context.Context, in *GetPostDynamicsRequest, opts ...grpc.CallOption) (*GetDynamicsResponse, error)
	// 3. Динамика лайков по посту
	GetPostLikesDynamics(ctx context.Context, in *GetPostDynamicsRequest, opts ...grpc.CallOption) (*GetDynamicsResponse, error)
	// 4. Динамика комментариев по посту
	GetPostCommentsDynamics(ctx context.Context, in *GetPostDynamicsRequest, opts ...grpc.CallOption) (*GetDynamicsResponse, error)
	// 5. Топ-10 постов по лайкам/просмотрам/комментам
	GetTopPosts(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopPostsResponse, error)
	// 6. Топ-10 пользователей по лайкам/просмотрам/комментам
	GetTopUsers(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopUsersResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*GetPostStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostStatsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostViewsDynamics(ctx context.Context, in *GetPostDynamicsRequest, opts ...grpc.CallOption) (*GetDynamicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDynamicsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostViewsDynamics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostLikesDynamics(ctx context.Context, in *GetPostDynamicsRequest, opts ...grpc.CallOption) (*GetDynamicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDynamicsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostLikesDynamics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostCommentsDynamics(ctx context.Context, in *GetPostDynamicsRequest, opts ...grpc.CallOption) (*GetDynamicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDynamicsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostCommentsDynamics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTopPosts(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopPostsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTopPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTopUsers(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopUsersResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTopUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
type StatisticsServiceServer interface {
	// 1. Получение общей статистики по посту
	GetPostStats(context.Context, *GetPostStatsRequest) (*GetPostStatsResponse, error)
	// 2. Динамика просмотров по посту
	GetPostViewsDynamics(context.Context, *GetPostDynamicsRequest) (*GetDynamicsResponse, error)
	// 3. Динамика лайков по посту
	GetPostLikesDynamics(context.Context, *GetPostDynamicsRequest) (*GetDynamicsResponse, error)
	// 4. Динамика комментариев по посту
	GetPostCommentsDynamics(context.Context, *GetPostDynamicsRequest) (*GetDynamicsResponse, error)
	// 5. Топ-10 постов по лайкам/просмотрам/комментам
	GetTopPosts(context.Context, *GetTopRequest) (*GetTopPostsResponse, error)
	// 6. Топ-10 пользователей по лайкам/просмотрам/комментам
	GetTopUsers(context.Context, *GetTopRequest) (*GetTopUsersResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) GetPostStats(context.Context, *GetPostStatsRequest) (*GetPostStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostStats not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostViewsDynamics(context.Context, *GetPostDynamicsRequest) (*GetDynamicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostViewsDynamics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostLikesDynamics(context.Context, *GetPostDynamicsRequest) (*GetDynamicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikesDynamics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostCommentsDynamics(context.Context, *GetPostDynamicsRequest) (*GetDynamicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostCommentsDynamics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTopPosts(context.Context, *GetTopRequest) (*GetTopPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPosts not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTopUsers(context.Context, *GetTopRequest) (*GetTopUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUsers not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetPostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostStats(ctx, req.(*GetPostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostViewsDynamics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDynamicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostViewsDynamics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostViewsDynamics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostViewsDynamics(ctx, req.(*GetPostDynamicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostLikesDynamics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDynamicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostLikesDynamics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostLikesDynamics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostLikesDynamics(ctx, req.(*GetPostDynamicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostCommentsDynamics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDynamicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostCommentsDynamics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostCommentsDynamics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostCommentsDynamics(ctx, req.(*GetPostDynamicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTopPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTopPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTopPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTopPosts(ctx, req.(*GetTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTopUsers(ctx, req.(*GetTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostStats",
			Handler:    _StatisticsService_GetPostStats_Handler,
		},
		{
			MethodName: "GetPostViewsDynamics",
			Handler:    _StatisticsService_GetPostViewsDynamics_Handler,
		},
		{
			MethodName: "GetPostLikesDynamics",
			Handler:    _StatisticsService_GetPostLikesDynamics_Handler,
		},
		{
			MethodName: "GetPostCommentsDynamics",
			Handler:    _StatisticsService_GetPostCommentsDynamics_Handler,
		},
		{
			MethodName: "GetTopPosts",
			Handler:    _StatisticsService_GetTopPosts_Handler,
		},
		{
			MethodName: "GetTopUsers",
			Handler:    _StatisticsService_GetTopUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/statistics.proto",
}
